export const initialState = [
  {
    id: 1,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20200715/53fa50226803f.jpg',
    name: '거창 오가네체리자두 3kg 한 상자',
    description: '거창 오가네체리자두\n * 3kg 한상자 (50개 내외)\n',
    origin: '대한민국',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '한상자 3kg',
        optionPrice: 29000,
        optionStock: 500,
      },
    ],
    price: 29000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 2,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220610/57a69b42b7edf.jpg',
    name: '목감기에 좋은 건더기 없는 프리미엄 수제 착즙 유자청',
    description:
      '완도 바람 맞고 자란 비타민 가득 유자를 청으로 만나보세요!\n 환절기에 딱! 목감기에 딱!',
    origin: '전라남도 완도',
    shipping: {
      shippingPrice: 3500,
      shippingBasis: 50000,
    },
    option: [
      {
        optionId: 1,
        optionName: '유자청 1kg 1병',
        optionPrice: 13300,
        optionStock: 20,
      },
    ],
    price: 13300,
    discountRate: 10,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 3,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/87364a62fbe94.jpg',
    name: '무농약 GAP 인증 국산 청양 블루베리',
    description: '충남의 알프스라 불리는 청정지역 청양에서\n 무농약으로 재배한 생 블루베리!',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '2kg',
        optionPrice: 52000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '4kg',
        optionPrice: 92000,
        optionStock: 5,
      },
    ],
    price: 52000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 4,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220520/a57222f5689fc.png',
    name: '물에 타먹는 제주 수제 감귤칩',
    description:
      '감귤을 즐기는 색다른 방법!\n 상큼함과 달달함이 고루 담겨진 바삭한 감귤칩을 만나보세요.\n',
    origin: '제주특별자치도 서귀포시',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '초코맛 50g',
        optionPrice: 25000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '딸기맛 55g',
        optionPrice: 30000,
        optionStock: 5,
      },
    ],
    price: 25000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 5,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/8bd6568d69b90.jpg',
    name: '전통 재래식 메주로 띄운 수제 된장',
    description:
      '국내산 청양 콩으로 만들어 더욱 맛있고 건강한 수제 된장\n 엄마의 마음으로 건강한 재료들을 엄선하고 준비하여 정성으로 담았습니다.',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '된장 1kg',
        optionPrice: 19000,
        optionStock: 30,
      },
      {
        optionId: 2,
        optionName: '된장 2kg',
        optionPrice: 29000,
        optionStock: 50,
      },
    ],
    price: 19000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 6,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20200715/53fa50226803f.jpg',
    name: '거창 오가네체리자두 3kg 한 상자',
    description: '거창 오가네체리자두\n * 3kg 한상자 (50개 내외)\n',
    origin: '대한민국',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '한상자 3kg',
        optionPrice: 29000,
        optionStock: 500,
      },
    ],
    price: 29000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 7,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220610/57a69b42b7edf.jpg',
    name: '목감기에 좋은 건더기 없는 프리미엄 수제 착즙 유자청',
    description:
      '완도 바람 맞고 자란 비타민 가득 유자를 청으로 만나보세요!\n 환절기에 딱! 목감기에 딱!',
    origin: '전라남도 완도',
    shipping: {
      shippingPrice: 3500,
      shippingBasis: 50000,
    },
    option: [
      {
        optionId: 1,
        optionName: '유자청 1kg 1병',
        optionPrice: 13300,
        optionStock: 20,
      },
    ],
    price: 13300,
    discountRate: 10,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 8,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/87364a62fbe94.jpg',
    name: '무농약 GAP 인증 국산 청양 블루베리',
    description: '충남의 알프스라 불리는 청정지역 청양에서\n 무농약으로 재배한 생 블루베리!',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '2kg',
        optionPrice: 52000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '4kg',
        optionPrice: 92000,
        optionStock: 5,
      },
    ],
    price: 52000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 9,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220520/a57222f5689fc.png',
    name: '물에 타먹는 제주 수제 감귤칩',
    description:
      '감귤을 즐기는 색다른 방법!\n 상큼함과 달달함이 고루 담겨진 바삭한 감귤칩을 만나보세요.\n',
    origin: '제주특별자치도 서귀포시',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '초코맛 50g',
        optionPrice: 25000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '딸기맛 55g',
        optionPrice: 30000,
        optionStock: 5,
      },
    ],
    price: 25000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 10,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/8bd6568d69b90.jpg',
    name: '전통 재래식 메주로 띄운 수제 된장',
    description:
      '국내산 청양 콩으로 만들어 더욱 맛있고 건강한 수제 된장\n 엄마의 마음으로 건강한 재료들을 엄선하고 준비하여 정성으로 담았습니다.',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '된장 1kg',
        optionPrice: 19000,
        optionStock: 30,
      },
      {
        optionId: 2,
        optionName: '된장 2kg',
        optionPrice: 29000,
        optionStock: 50,
      },
    ],
    price: 19000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 11,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20200715/53fa50226803f.jpg',
    name: '거창 오가네체리자두 3kg 한 상자',
    description: '거창 오가네체리자두\n * 3kg 한상자 (50개 내외)\n',
    origin: '대한민국',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '한상자 3kg',
        optionPrice: 29000,
        optionStock: 500,
      },
    ],
    price: 29000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 12,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220610/57a69b42b7edf.jpg',
    name: '목감기에 좋은 건더기 없는 프리미엄 수제 착즙 유자청',
    description:
      '완도 바람 맞고 자란 비타민 가득 유자를 청으로 만나보세요!\n 환절기에 딱! 목감기에 딱!',
    origin: '전라남도 완도',
    shipping: {
      shippingPrice: 3500,
      shippingBasis: 50000,
    },
    option: [
      {
        optionId: 1,
        optionName: '유자청 1kg 1병',
        optionPrice: 13300,
        optionStock: 20,
      },
    ],
    price: 13300,
    discountRate: 10,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 13,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/87364a62fbe94.jpg',
    name: '무농약 GAP 인증 국산 청양 블루베리',
    description: '충남의 알프스라 불리는 청정지역 청양에서\n 무농약으로 재배한 생 블루베리!',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '2kg',
        optionPrice: 52000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '4kg',
        optionPrice: 92000,
        optionStock: 5,
      },
    ],
    price: 52000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 14,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220520/a57222f5689fc.png',
    name: '물에 타먹는 제주 수제 감귤칩',
    description:
      '감귤을 즐기는 색다른 방법!\n 상큼함과 달달함이 고루 담겨진 바삭한 감귤칩을 만나보세요.\n',
    origin: '제주특별자치도 서귀포시',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '초코맛 50g',
        optionPrice: 25000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '딸기맛 55g',
        optionPrice: 30000,
        optionStock: 5,
      },
    ],
    price: 25000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 15,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/8bd6568d69b90.jpg',
    name: '전통 재래식 메주로 띄운 수제 된장',
    description:
      '국내산 청양 콩으로 만들어 더욱 맛있고 건강한 수제 된장\n 엄마의 마음으로 건강한 재료들을 엄선하고 준비하여 정성으로 담았습니다.',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '된장 1kg',
        optionPrice: 19000,
        optionStock: 30,
      },
      {
        optionId: 2,
        optionName: '된장 2kg',
        optionPrice: 29000,
        optionStock: 50,
      },
    ],
    price: 19000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 16,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20200715/53fa50226803f.jpg',
    name: '거창 오가네체리자두 3kg 한 상자',
    description: '거창 오가네체리자두\n * 3kg 한상자 (50개 내외)\n',
    origin: '대한민국',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '한상자 3kg',
        optionPrice: 29000,
        optionStock: 500,
      },
    ],
    price: 29000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 17,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220610/57a69b42b7edf.jpg',
    name: '목감기에 좋은 건더기 없는 프리미엄 수제 착즙 유자청',
    description:
      '완도 바람 맞고 자란 비타민 가득 유자를 청으로 만나보세요!\n 환절기에 딱! 목감기에 딱!',
    origin: '전라남도 완도',
    shipping: {
      shippingPrice: 3500,
      shippingBasis: 50000,
    },
    option: [
      {
        optionId: 1,
        optionName: '유자청 1kg 1병',
        optionPrice: 13300,
        optionStock: 20,
      },
    ],
    price: 13300,
    discountRate: 10,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 18,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/87364a62fbe94.jpg',
    name: '무농약 GAP 인증 국산 청양 블루베리',
    description: '충남의 알프스라 불리는 청정지역 청양에서\n 무농약으로 재배한 생 블루베리!',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '2kg',
        optionPrice: 52000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '4kg',
        optionPrice: 92000,
        optionStock: 5,
      },
    ],
    price: 52000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 19,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220520/a57222f5689fc.png',
    name: '물에 타먹는 제주 수제 감귤칩',
    description:
      '감귤을 즐기는 색다른 방법!\n 상큼함과 달달함이 고루 담겨진 바삭한 감귤칩을 만나보세요.\n',
    origin: '제주특별자치도 서귀포시',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '초코맛 50g',
        optionPrice: 25000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '딸기맛 55g',
        optionPrice: 30000,
        optionStock: 5,
      },
    ],
    price: 25000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 20,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220520/283df683851b8.png',
    name: '100% 제주감귤주스',
    description: '감귤을 즐기는 색다른 방법, 100% 착즙으로 마시는 감귤\n',
    origin: '제주특별자치도 서귀포시',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '15팩 x 1box',
        optionPrice: 22500,
        optionStock: 30,
      },
    ],
    price: 22500,
    discountRate: 5,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 21,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20200715/53fa50226803f.jpg',
    name: '거창 오가네체리자두 3kg 한 상자',
    description: '거창 오가네체리자두\n * 3kg 한상자 (50개 내외)\n',
    origin: '대한민국',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '한상자 3kg',
        optionPrice: 29000,
        optionStock: 500,
      },
    ],
    price: 29000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 22,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220610/57a69b42b7edf.jpg',
    name: '목감기에 좋은 건더기 없는 프리미엄 수제 착즙 유자청',
    description:
      '완도 바람 맞고 자란 비타민 가득 유자를 청으로 만나보세요!\n 환절기에 딱! 목감기에 딱!',
    origin: '전라남도 완도',
    shipping: {
      shippingPrice: 3500,
      shippingBasis: 50000,
    },
    option: [
      {
        optionId: 1,
        optionName: '유자청 1kg 1병',
        optionPrice: 13300,
        optionStock: 20,
      },
    ],
    price: 13300,
    discountRate: 10,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 23,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220520/a57222f5689fc.png',
    name: '물에 타먹는 제주 수제 감귤칩',
    description:
      '감귤을 즐기는 색다른 방법!\n 상큼함과 달달함이 고루 담겨진 바삭한 감귤칩을 만나보세요.\n',
    origin: '제주특별자치도 서귀포시',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '초코맛 50g',
        optionPrice: 25000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '딸기맛 55g',
        optionPrice: 30000,
        optionStock: 5,
      },
    ],
    price: 25000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 24,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/87364a62fbe94.jpg',
    name: '무농약 GAP 인증 국산 청양 블루베리',
    description: '충남의 알프스라 불리는 청정지역 청양에서\n 무농약으로 재배한 생 블루베리!',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '2kg',
        optionPrice: 52000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '4kg',
        optionPrice: 92000,
        optionStock: 5,
      },
    ],
    price: 52000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 25,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/8bd6568d69b90.jpg',
    name: '전통 재래식 메주로 띄운 수제 된장',
    description:
      '국내산 청양 콩으로 만들어 더욱 맛있고 건강한 수제 된장\n 엄마의 마음으로 건강한 재료들을 엄선하고 준비하여 정성으로 담았습니다.',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '된장 1kg',
        optionPrice: 19000,
        optionStock: 30,
      },
      {
        optionId: 2,
        optionName: '된장 2kg',
        optionPrice: 29000,
        optionStock: 50,
      },
    ],
    price: 19000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 26,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20200715/53fa50226803f.jpg',
    name: '거창 오가네체리자두 3kg 한 상자',
    description: '거창 오가네체리자두\n * 3kg 한상자 (50개 내외)\n',
    origin: '대한민국',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '한상자 3kg',
        optionPrice: 29000,
        optionStock: 500,
      },
    ],
    price: 29000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 27,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220610/57a69b42b7edf.jpg',
    name: '목감기에 좋은 건더기 없는 프리미엄 수제 착즙 유자청',
    description:
      '완도 바람 맞고 자란 비타민 가득 유자를 청으로 만나보세요!\n 환절기에 딱! 목감기에 딱!',
    origin: '전라남도 완도',
    shipping: {
      shippingPrice: 3500,
      shippingBasis: 50000,
    },
    option: [
      {
        optionId: 1,
        optionName: '유자청 1kg 1병',
        optionPrice: 13300,
        optionStock: 20,
      },
    ],
    price: 13300,
    discountRate: 10,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 28,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/87364a62fbe94.jpg',
    name: '무농약 GAP 인증 국산 청양 블루베리',
    description: '충남의 알프스라 불리는 청정지역 청양에서\n 무농약으로 재배한 생 블루베리!',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '2kg',
        optionPrice: 52000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '4kg',
        optionPrice: 92000,
        optionStock: 5,
      },
    ],
    price: 52000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 29,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220520/a57222f5689fc.png',
    name: '물에 타먹는 제주 수제 감귤칩',
    description:
      '감귤을 즐기는 색다른 방법!\n 상큼함과 달달함이 고루 담겨진 바삭한 감귤칩을 만나보세요.\n',
    origin: '제주특별자치도 서귀포시',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '초코맛 50g',
        optionPrice: 25000,
        optionStock: 10,
      },
      {
        optionId: 2,
        optionName: '딸기맛 55g',
        optionPrice: 30000,
        optionStock: 5,
      },
    ],
    price: 25000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
  {
    id: 30,
    imageUrl: 'https://cdn.imweb.me/thumbnail/20220622/8bd6568d69b90.jpg',
    name: '전통 재래식 메주로 띄운 수제 된장',
    description:
      '국내산 청양 콩으로 만들어 더욱 맛있고 건강한 수제 된장\n 엄마의 마음으로 건강한 재료들을 엄선하고 준비하여 정성으로 담았습니다.',
    origin: '충청남도 청양군',
    shipping: {
      shippingPrice: '무료 배송',
      shippingBasis: 3000,
    },
    option: [
      {
        optionId: 1,
        optionName: '된장 1kg',
        optionPrice: 19000,
        optionStock: 30,
      },
      {
        optionId: 2,
        optionName: '된장 2kg',
        optionPrice: 29000,
        optionStock: 50,
      },
    ],
    price: 19000,
    discountRate: 15,
    isDisplay: true,
    isLiked: false,
  },
];
